# Generated by Django 4.2.9 on 2024-01-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klachtsysteem', '0003_status_klacht_afbeelding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klacht',
            name='omschrijving',
            field=models.CharField(max_length=300),
        ),
    ]
